# في ملف .github/workflows/build.yml
     name: Build APK
     on: [push]
     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - uses: subosito/flutter-action@v2
           - run: flutter build apk
           - uses: actions/upload-artifact@v3
             with:
               name: app-release.apk
               path: build/app/outputs/flutter-apk/app-release.apk
