name: Custom Flutter APK Builder
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.29.2"
      JAVA_VERSION: "17"
      GRADLE_VERSION: "7.6.3"
      NDK_VERSION: "27.0.12077973"
      COMPILE_SDK: "33"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          build-tools-version: "33.0.2"
          ndk-version: ${{ env.NDK_VERSION }}
          platforms: "android-${{ env.COMPILE_SDK }}"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Force Latest file_picker
        run: |
          flutter pub add file_picker:any
          flutter pub upgrade file_picker

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
