name: Stable APK Builder
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.29.2"

    steps:
      - uses: actions/checkout@v4

      - name: Set Gradle Version
        run: |
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6.3-bin.zip" > android/gradle/wrapper/gradle-wrapper.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Apply Critical Fixes
        run: |
          FILE_PICKER_PATH=$(find ${{ github.workspace }}/.pub-cache/hosted/pub.dev -type d -name "file_picker-*" | head -n 1)
          find "$FILE_PICKER_PATH" -name 'FilePickerPlugin.java' -exec sed -i \
          's/PluginRegistry.Registrar/FlutterPlugin.FlutterPluginBinding/g;
           s/registrar.activity()/binding.getActivity()/g;
           s/registrar.context()/binding.getApplicationContext()/g' {} \;

          sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 33/g' android/app/build.gradle

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk