name: Stable APK Builder
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FLUTTER_VERSION: "3.29.2"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # لسحب كل التاريخ

      - name: Restore Lock File
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            pubspec.lock
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Enforce Dependencies
        run: |
          flutter pub get --no-upgrade
          if grep -q '^  file_picker:' pubspec.lock; then
            echo "File picker version locked successfully"
          else
            echo "Error: file_picker not in lockfile"
            exit 1
          fi

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons