name: Fixed NDK Build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.29.2"
      NDK_VERSION: "27.0.12077973"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Clean NDK Cache
        run: sudo rm -rf $ANDROID_HOME/ndk/25.*

      - name: Install Correct NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          build-tools-version: "33.0.2"
          platforms: "android-33"

      - name: Force NDK Version
        run: |
          sdkmanager --uninstall "ndk;25.1.8937393"
          sdkmanager --install "ndk;${{ env.NDK_VERSION }}" --verbose
          echo "ndk.dir=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}" >> android/local.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
